# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Test and Check Binary

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-bin:
    name: Check Dist has been Updated
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Copy of action.yaml to use paths correctly
      - name: Get Story Numbers
        id: stories
        if: ${{ inputs.changelog }} = 'true'
        uses: Renddslow/prepare-branch-commit@v1.0.1
        with:
          branch-name: ${{ github.head_ref }}

      - name: Get TODOs
        id: todos
        if: ${{ inputs.changelog }} = 'true'
        # Find all comments with matching story numbers
        # Results concatenated with ':::' to support single line requirement
        run: |
          echo "::set-output name=todo-files::$(echo "${{ steps.stories.outputs.issue-tags }}" | tr ',' '\n' | xargs -I {} sh -c "grep -n '.*\bTODO.*{}' -R . --exclude-dir 'node_modules' || true" | awk '{print}' ORS='_:::_')"
        shell: bash

      - name: Code Review
        run: node ./bin/index.js
        shell: bash
        env:
          BASE_DIR: ${{ github.workflow_root }}
          CODE_REVIEW_CHANGELOG: 'false'
          CODE_REVIEW_TODOS: ${{ inputs.todos }}
          CODE_REVIEW_TOKEN: ${{ secrets.PUBLIC_GHA_ACCESS_TOKEN }}
          PR_BRANCH: ${{ github.head_ref }}
          STORY_NUMBERS: ${{ steps.stories.outputs.issue-tags }}
          TODO_COMMENTS: ${{ steps.todos.outputs.todo-files }}

      - name: Node
        id: node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
        shell: bash

      - name: Test
        run: yarn test
        shell: bash

      - name: Rebuild the index.js file
        run: yarn build
        shell: bash

      - name: Compare the expected and actual dist/ directories
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol bin/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See attached artifacts and status below:"
            git diff
            exit 1
          fi
        shell: bash

      # If bin/ was different from expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v2
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: bin
          path: bin/
